name: create stale issue after 1 day

on:
  schedule:
    - cron: '* * * * *'

permissions:
  contents: read
  issues: write

jobs:
  raise_stale_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}